---
- name: Restart
  hosts: app
  become: true

  roles:
      - go-app-service-stop
      - docker-monitoring-stop
      - docker-compose-redis-sentinel-stop
      - postgres-stop
      - postgres-start
      - docker-compose-redis-sentinel-start
      - docker-monitoring-start
      - go-app-service-start
