---
- name: Create environment file for the application
  ansible.builtin.template:
      src: app.env.j2
      dest: "/etc/{{ go_app_service_name }}.env"
      owner: root
      group: root
      mode: "0600"

- name: Create systemd unit for Go application
  ansible.builtin.template:
      src: go-app.service.j2
      dest: "/etc/systemd/system/{{ go_app_service_name }}.service"
      owner: root
      group: root
      mode: "0644"

- name: Create logrotated unit for Go application
  ansible.builtin.template:
      src: go-app-logrotate.j2
      dest: "/etc/logrotate.d/{{ go_app_service_name }}"
      owner: root
      group: root
      mode: "0644"

- name: Reload systemd configuration
  ansible.builtin.systemd:
      daemon_reload: true

- name: Enable and start Go application service
  ansible.builtin.service:
      name: "{{ go_app_service_name }}"
      state: started
      enabled: true
