name: Deploy to Server

on:
    push:
        branches: [master]

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install Ansible
              run: |
                  pip install ansible
                  # Если нужны коллекции
                  ansible-galaxy collection install community.docker

            - name: Setup SSH key
              env:
                  SERVER_IP: ${{ secrets.SERVER_IP }}
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              run: |
                  mkdir -p ~/.ssh
                  echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

            - name: Create vault password file
              env:
                  ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
              run: echo "${ANSIBLE_VAULT_PASSWORD}" > ./ansible/vault_pass.txt

            - name: Run Ansible playbook
              uses: dawidd6/action-ansible-playbook@v2
              with:
                  playbook: playbooks/full-app-setup.yml
                  directory: ./ansible
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  inventory: |
                      [app]
                      ${{ secrets.SERVER_IP }} ansible_user=andrey
                  options: |
                      --extra-vars "target_host=${{ secrets.SERVER_IP }} ansible_become_pass=${{ secrets.SUDO_PASSWORD }}"
                      --vault-password-file ./vault_pass.txt
